### ISSUE TITLE
milestone functionality like freelancer

### ISSUE THREAD

**Issue by jyotisuntech** [paypal/SDKs#53]
Can you provide me the php code or an API for the paypal milestone  payment functionality like freelancer.com website. I want to create a functionality in my website that client will a milestone payment first and that amount get freezed and it will transfer to supplier acount after project completion.Please suggest me how to implement it in php.

**Comment by tomwhipple** [comment]
Please see the [PHP SDK](/paypal/PayPal-PHP-SDK).
